import mongoose from "mongoose";

const stockFinancialsSchema = new mongoose.Schema({
  symbol: String,
  companyNameEN: String,
  companyNameAR: String,
  market_type: String,
  tradingNameEn: String,
  tradingNameAr: String,
  balanceSheet: [
    {
      year: String,
      current_assets: String,
      inventory: String,
      investments: String,
      fixed_assets: String,
      other_assets: String,
      total_assets: String,
      current_liabilities: String,
      non_current_liabilities: String,
      other_liabilities: String,
      shareholders_equity: String,
      total_liabilities_and_shareholder_equity: String,
      minority_interests: String,
      figures_in: String,
      currency_in: String,
      last_update_date: String,
    },
  ],
  balanceSheetQuarterly: [
    {
      year: String,
      current_assets: String,
      inventory: String,
      investments: String,
      fixed_assets: String,
      other_assets: String,
      total_assets: String,
      current_liabilities: String,
      non_current_liabilities: String,
      other_liabilities: String,
      shareholders_equity: String,
      total_liabilities_and_shareholder_equity: String,
      minority_interests: String,
      figures_in: String,
      currency_in: String,
      last_update_date: String,
    },
  ],
  incomeSheet: [
    {
      year: String,
      sales: String,
      sales_cost: String,
      total_income: String,
      other_revenues: String,
      total_revenues: String,
      admin_marketing_expenses: String,
      depreciation: String,
      other_expenses: String,
      total_expenses: String,
      net_income_before_zakat: String,
      zakat: String,
      net_income: String,
      balance_first_period: String,
      reserves: String,
      cash_dividends: String,
      other_distributions: String,
      balance_end_period: String,
      figures_in: String,
      currency_in: String,
      last_update_date: String,
    },
  ],
  incomeSheetQuarterly: [
    {
      year: String,
      sales: String,
      sales_cost: String,
      total_income: String,
      other_revenues: String,
      total_revenues: String,
      admin_marketing_expenses: String,
      depreciation: String,
      other_expenses: String,
      total_expenses: String,
      net_income_before_zakat: String,
      zakat: String,
      net_income: String,
      balance_first_period: String,
      reserves: String,
      cash_dividends: String,
      other_distributions: String,
      balance_end_period: String,
      figures_in: String,
      currency_in: String,
      last_update_date: String,
    },
  ],
  cashFlow: [
    {
      year: String,
      net_income: String,
      depreciation: String,
      accounts_receivable: String,
      inventory: String,
      prepaid_expenses: String,
      accounts_payable: String,
      other_changes_operating_activity: String,
      purchases_fixed_assets: String,
      other_changes_investing_activity: String,
      increase_in_debts: String,
      other_changes_financing_activity: String,
      cash_beginning_period: String,
      cash_end_period: String,
      figures_in: String,
      currency_in: String,
      last_update_date: String,
    },
  ],
  cashFlowQuarterly: [
    {
      year: String,
      net_income: String,
      depreciation: String,
      accounts_receivable: String,
      inventory: String,
      prepaid_expenses: String,
      accounts_payable: String,
      other_changes_operating_activity: String,
      purchases_fixed_assets: String,
      other_changes_investing_activity: String,
      increase_in_debts: String,
      other_changes_financing_activity: String,
      cash_beginning_period: String,
      cash_end_period: String,
      figures_in: String,
      currency_in: String,
      last_update_date: String,
    },
  ],
  dividends: [
    {
      announced_date: String,
      eligibility_date: String,
      distribution_date: String,
      distribution_way: String,
      dividend_per_share: String,
    },
  ],
});

const StockFinancials = mongoose.model(
  "StockFinancials",
  stockFinancialsSchema
);

export default StockFinancials;
